import { environment } from 'src/environments/environment.prod'

let baseUrl = environment.apiUrl
let baseURL = environment.apiURL

export const URI = {
  signup: baseUrl + 'signup',
  verifyEmail: baseUrl + 'EmailVerification',
  login: baseUrl + 'login',
  forgetPassword: baseUrl + 'forgotPassword',
  //validateSocialLogin: baseUrl + 'socialloginvalidation',
  socialLogin: baseUrl + 'SocialLogin',
  updateProfile: baseUrl + 'profileUpdate/',
  getSkills: baseURL + 'skills/GetKeySkills',
  getProfile: baseUrl + 'get-profile',
  getUserbyId: baseUrl + 'Details/',
  resentOtp: baseUrl + 'sendotp',
  resendOTPCr: baseURL + 'corporate-user/SendOtp',
 // forgetPassword: baseUrl + 'ForgotPassword',
  changePassowrd: baseUrl + 'changepassword/',
  addUserCertification: baseUrl + 'AddUserCertification',
  getUserCertification: baseUrl + 'GetUserCertificationsByUserId/',
  getUserProject: baseUrl + 'GetUserProjectsByUserId/',
  addProject: baseUrl + 'AddUserProject',
  corporateSignup: baseURL + 'corporate-user/Signup',
  crEmailVerify: baseURL + 'corporate-user/emailVerification',
  crLogin: baseURL + 'corporate-user/login',
  GetActiveJobListingPagedList:
    baseURL + 'job-listing/GetActiveJobListingPagedList',
  GetActiveJobWorkshopPagedList:
    baseURL + 'job-listing/getActiveWorkshopListingPagedList',
  GetActiveJobInternshipPagedList:
    baseURL + 'job-listing/getActiveInternshipListingPagedList',
  // getJobsForOpenListing: baseURL + 'job-listing/getJobsForOpenListing',
  getJobsForOpenListing: baseURL + 'job-listing/Searchjobs',
  getCompanyType: baseURL + 'company/GetActiveCompanyTypesList',
  cr_profile: baseURL + 'corporate-user/ProfileUpdate/',
  getEmploymentDetailsByUserId: baseUrl + 'GetUserEmploymentsByUserId/',
  addUserEmployment: baseUrl + 'AddUserEmployment',
  UpdateUserEmployment: baseUrl + 'UpdateUserEmployment/',
  UpdateUserProject: baseUrl + 'UpdateUserProject/',
  UpdateUserCertification: baseUrl + 'UpdateUserCertification/',
  DeleteUserEmployment: baseUrl + 'DeleteUserEmployment/',
  DeleteUserProject: baseUrl + 'DeleteUserProject/',
  DeleteUserCertification: baseUrl + 'DeleteUserCertification/',
  ApplyJob: baseUrl + 'AddUserApplication',
  GetUserApplicationsByUserId: baseUrl + 'GetUserApplicationsByUserId/',
  addJob: baseURL + 'job-listing/AddJobListing',
  getJobtype: baseURL + 'job-types/GetJobType',
  getjobpostedByuser: baseURL + 'job-listing/GetJobListingPagedList/',
  crChangePassword: baseURL + 'corporate-user/changepassword/',
  updateAddJob: baseURL + 'job-listing/UpdateJobListing/',
  getJobListingById: baseURL + 'job-listing/getJobListingById/',
  GetJobLocationSuggestions: baseURL + 'job-listing/GetJobLocationSuggestions/',
  addEducation: baseURL + 'user-education/AddUserEducation',
  getEducationById: baseURL + 'user-education/GetUserEducationByUserId',
  edituserEducation: baseURL + 'user-education/UpdateUserEducation/',
  deleteUserEducation: baseURL + 'user-education/DeleteUserEducation/',
  crForgotPassword: baseURL + 'corporate-user/forgotPassword',
  corporateDetails: baseURL + 'corporate-user/details/',
  getRecommendedJobsForUser: baseURL + 'job-listing/GetRecommendedJobsForUser',
  changeUserAppStatus: baseUrl + 'ChangeUserApplicationStatus',
  getApplicationStatus: baseURL + 'application-status/GetApplicationStatus',
  getCorporateList:baseURL+'corporate-user/getusers',
  getUsersList:baseUrl+'getUsers',
  getPaymentPlans:baseURL+'payment-plans/GetPaymentPlans',
  makePayment:baseURL+'payments/quazi-payment',
  paymentSuccess:baseURL+'payments/quazi-payment-success'
}
